//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaBaby
{
    using System;
    using System.Collections.Generic;
    
    public partial class Album
    {
        public Album()
        {
            this.AlbumMedias = new HashSet<AlbumMedia>();
        }
    
        public int ID { get; set; }
        public string AlbumName { get; set; }
        public string URL { get; set; }
    
        public virtual ICollection<AlbumMedia> AlbumMedias { get; set; }
    }
}
