//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaBaby
{
    using System;
    using System.Collections.Generic;
    
    public partial class FirstThingDetail
    {
        public int ID { get; set; }
        public string Body { get; set; }
        public int FirstId { get; set; }
    
        public virtual FirstThing FirstThing { get; set; }
    }
}
