//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RezaBaby
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RezaDBEntities : DbContext
    {
        public RezaDBEntities()
            : base("name=RezaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FirstThing> FirstThing { get; set; }
        public virtual DbSet<FirstThingDetail> FirstThingDetails { get; set; }
        public virtual DbSet<FirstThingMedia> FirstThingMedias { get; set; }
        public virtual DbSet<Album> Albums { get; set; }
        public virtual DbSet<AlbumMedia> AlbumMedias { get; set; }
    }
}
